title = "'Wild' theme shell for Hugo by WTG"
copyright = "© 2023 Wild Tech 'Garden'"
description = "The Hugo shell module for themes by Wild Tech 'Garden' (WTG)"

[params]
cssColourScheme = "default"

[module]
[module.hugoVersion]
extended = false
min = "v0.117.0"
