title = "'Wild' theme shell for Hugo by WTG"
copyright = "© 2023 Wild Tech 'Garden'"
description = "The Hugo shell module for themes by Wild Tech 'Garden' (WTG)"

[params]
cssColourScheme = "default"

[module]
[module.hugoVersion]
extended = false
min = "v0.117.0"

[[module.mounts]]
source = "static"
target = "static"

[[module.mounts]]
source = "layouts"
target = "layouts"

[[module.mounts]]
source = "data"
target = "data"

[[module.mounts]]
source = "assets"
target = "assets"

[[module.mounts]]
source = "i18n"
target = "i18n"

[[module.mounts]]
source = "archetypes"
target = "archetypes"

